name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  package_ubuntu_20_04:
    name: Build deb-20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install \
          libasound-dev libudev-dev libclang-dev libhunspell-dev pkg-config
      - name: Install cargo-deb
        run: cargo install cargo-deb || true
      - name: Package DEB
        run: cargo deb
      - name: Set .deb path
        id: deb_path
        run: |
          ls -1 target/debian/*.deb | awk '{print "::set-output name=deb_path::"$1}'
      - name: Create/Update release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.deb_path.outputs.deb_path }}
          allowUpdates: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: blightmud-deb-20.04
          path: ${{ steps.deb_path.outputs.deb_path }}

  package_ubuntu_22_04:
    name: Build deb-22.04 & RPM
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install \
          libasound-dev libudev-dev libclang-dev libhunspell-dev pkg-config rpm
      - name: Install cargo-deb
        run: cargo install cargo-deb || true
      - name: Install cargo-rpm
        run: cargo install cargo-rpm || true
      - name: Package DEB
        run: cargo deb
      - name: Set .deb path
        id: deb_path
        run: |
          ls -1 target/debian/*.deb | awk '{print "::set-output name=deb_path::"$1}'
      - name: Package RPM
        run: cargo rpm build
      - name: Set .rpm path
        id: rpm_path
        run: |
          ls -1 target/release/rpmbuild/RPMS/x86_64/*.rpm | awk '{print "::set-output name=rpm_path::"$1}'
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          onlyLastTag: true
          filterByMilestone: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create/Update release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: ${{ steps.deb_path.outputs.deb_path }},${{ steps.rpm_path.outputs.rpm_path }}
          bodyFile: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: blightmud-deb-22.04
          path: ${{ steps.deb_path.outputs.deb_path }}
      - name: Upload rpm
        uses: actions/upload-artifact@v3
        with:
          name: blightmud-rpm
          path: ${{ steps.rpm_path.outputs.rpm_path }}

  build_macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build release
        run: cargo build --release --locked
      - name: Get current version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Package Binary
        run: cd target/release && zip -r blightmud-${{ steps.get_version.outputs.VERSION }}-macos.zip blightmud
      - name: Create/Update release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          omitBody: true
          artifacts: target/release/blightmud-${{ steps.get_version.outputs.VERSION }}-macos.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: blightmud-macos
          path: target/release/blightmud-${{ steps.get_version.outputs.VERSION }}-macos.zip
