name: Test & Build

on:
  pull_request:
  push:
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly]
        include:
          - os: macos-latest
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            ~/.cargo/bin
            ./target
          key: ${{ matrix.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            ~/.cargo/bin
          key: ${{ matrix.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Updating repository
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update
      - name: Installing dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libasound2-dev libspeechd-dev
      - name: Setup toolchain
        if: ${{ matrix.toolchain != 'nightly' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
          override: true
      - name: Setup toolchain
        if: ${{ matrix.toolchain == 'nightly' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
      - name: Test
        run: |
          cargo test --release --test lua_tests --test validation_tests
          cargo test --release --test lua_tests --test validation_tests
          cargo test --release --test lua_tests --test validation_tests
          cargo test --release --test lua_tests --test validation_tests
          cargo test --release --test lua_tests --test validation_tests
          cargo test --release --test lua_tests --test validation_tests
          cargo test --release --test lua_tests --test validation_tests
          cargo test --release --test lua_tests --test validation_tests
          cargo test --release --test lua_tests --test validation_tests
          cargo test --release --test lua_tests --test validation_tests
