name: Test & Build

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - "*_impl"

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-13, macos-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly]
        include:
          - os: macos-latest
          - os: macos-11
          - os: macos-13
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ matrix.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('Cargo.*') }}
      - name: Updating repository
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update
      - name: Installing dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libasound2-dev libspeechd-dev
      - name: Setup toolchain
        if: ${{ matrix.toolchain != 'nightly' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
          override: true
      - name: Setup toolchain
        if: ${{ matrix.toolchain == 'nightly' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
      - name: Test
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cargo test --locked
      - name: Test (all features)
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: cargo test --locked --all-features
      - name: Test release (all features)
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: cargo test --release --locked --all-features
      - name: Build
        run: cargo build --release --locked
      - name: Build (all features)
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: cargo build --release --locked --all-features
